name: Merge JSON Files

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  merge-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jq

    - name: Merge JSON files
      run: |
        # Combine all JSON files into one array
        jq -s 'add' result/vn/*.json > merged.json

    - name: Commit merged file
      run: |
    - name: Commit merged file
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add merged.json
        git commit -m "Merged JSON files"
        git push origin HEAD:main
    env:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
